name       : encfs
version    : 1.9.1
release    : 2
source     :
    - https://github.com/vgough/encfs/releases/download/v1.9.1/encfs-1.9.1.tar.gz : 67203aeff7a06ce7be83df4948db296be89a00cffe1108a0a41c96d7481106a4
license    :
    - GPL-3.0
    - LGPL-3.0
    - MIT
    - Zlib
component  : system.utils
summary    : Userspace encrypted filesystem
description: |
    EncFS provides an encrypted filesystem in user-space. It runs in userspace, using the FUSE library for the filesystem interface.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(tinyxml2)
setup      : |
    mkdir build
    pushd build
    %cmake -DBUILD_SHARED_LIBS=ON -DUSE_INTERNAL_TINYXML=OFF -DINSTALL_LIBENCFS=ON -DLIB_INSTALL_DIR:PATH=%libdir% ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
