name       : encfs
version    : 1.9.4
release    : 6
source     :
    - https://github.com/vgough/encfs/archive/v1.9.4.tar.gz : 20656b4ead58ebd8d5f49a5c346b59e70dc2dc31220159e5b5a115bfa1bc40d6
license    :
    - GPL-3.0
    - LGPL-3.0
    - MIT
component  : system.utils
summary    : Userspace encrypted filesystem
description: |
    EncFS provides an encrypted filesystem in user-space. It runs in userspace, using the FUSE library for the filesystem interface.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(tinyxml2)
setup      : |
    mkdir build && cd build
    %cmake .. \
        -DBUILD_STATIC_LIBS=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_INTERNAL_TINYXML=OFF \
        -DINSTALL_LIBENCFS=ON \
        -DLIB_INSTALL_DIR:PATH=%libdir%
build      : |
    %make -C build
    %make -C build/test
install    : |
    %make_install -C build
check      : |
    ./build/test/unittests

