name       : encfs
version    : 1.9.5
release    : 12
source     :
    - https://github.com/vgough/encfs/archive/v1.9.5.tar.gz : 4709f05395ccbad6c0a5b40a4619d60aafe3473b1a79bafb3aa700b1f756fd63
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Userspace encrypted filesystem
description: |
    EncFS provides an encrypted filesystem in user-space. It runs in userspace, using the FUSE library for the filesystem interface.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(tinyxml2)
setup      : |
    mkdir build && cd build
    %cmake .. \
        -DBUILD_STATIC_LIBS=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_INTERNAL_TINYXML=OFF \
        -DINSTALL_LIBENCFS=ON \
        -DLIB_INSTALL_DIR:PATH=%libdir%
build      : |
    %make -C build
    %make -C build/test
install    : |
    %make_install -C build
check      : |
    ./build/test/unittests
