name       : encfs
version    : 1.9.2
release    : 4
source     :
    - https://github.com/vgough/encfs/archive/v1.9.2.tar.gz : cd9e972cd9565cdc26473c86d2c77c98de31fc6f604fa7d149dd5d6e35d46eaa
license    :
    - GPL-3.0
    - LGPL-3.0
    - MIT
component  : system.utils
summary    : Userspace encrypted filesystem
description: |
    EncFS provides an encrypted filesystem in user-space. It runs in userspace, using the FUSE library for the filesystem interface.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(tinyxml2)
setup      : |
    mkdir build
    pushd build
    %cmake -DBUILD_SHARED_LIBS=ON -DUSE_INTERNAL_TINYXML=OFF -DINSTALL_LIBENCFS=ON -DLIB_INSTALL_DIR:PATH=%libdir% ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd

    # https://github.com/vgough/encfs/issues/224
    chmod +x $installdir/usr/bin/encfssh
